### ISSUE TITLE
Debugging arduino with EclipseMars for win7 ,vitualbox 5.0, ubuntu 14.04 : add pgmspace.h file

### ISSUE THREAD

**Issue by kshok** [jantje/hardware#2]
My target is arduino1.6.1 debugging that use eclipseMars for  win7 ,vitualbox 5.0, ubuntu 14.04 .
   • Eclipse IDE for C/C++ Developers mars 64bit
   • plugin : Arduino Eclipse Extensions 2.4
   • Arduino 1.6.1
   • win7: 64bit
   • Oracle VM VirtualBox 5.0
   • Ubuntu 14.04

I was follow http://blog.baeyens.it/#comments23 .

I have success this step
 [Compile the project in the debug configuration (this is not strictly needed but it makes it easier to fill in the following forms)]
![20150718_1success](https://cloud.githubusercontent.com/assets/13166935/8760198/e7232fcc-2d49-11e5-81e2-8eb6ad726246.png)

next step  [Now we'll create a debug configuration for our debugDemo project using the "jantje hardware".]
![20150718_fail1](https://cloud.githubusercontent.com/assets/13166935/8760093/9449c9a0-2d44-11e5-97c0-d14ebceb398f.png)

also next step is fail . [Right click the project->build configurations->build all.]
Missing file or directory
![20150718_fail2](https://cloud.githubusercontent.com/assets/13166935/8760121/2ad36a6a-2d46-11e5-8c6f-4a23639f0b70.png)

What can I do for next?

**Comment by jantje** [comment]
please provide console output.

**Comment by kshok** [comment]
Hi.
Console output is here

09:57:20 ***\* Build of configuration Debug for project debugDemo ****
make all 
Building file: ../.ino.cpp
Starting C++ compile
"g++" -c -g -O0 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -DF_CPU=16000000L -DARDUINO=10601 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR_LOCAL   -DLOCAL_RUN   -I"/opt/arduino-1.6.1/hardware/jantje/avr_local/cores/arduino" -I"/opt/arduino-1.6.1/hardware/jantje/avr_local/variants/standard" -MMD -MP -MF".ino.cpp.d" -MT".ino.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "../.ino.cpp"  -o  ".ino.cpp.o"   -Wall
In file included from /opt/arduino-1.6.1/hardware/jantje/avr_local/cores/arduino/Arduino.h:17:0,
                 from ../.ino.cpp:6:
/opt/arduino-1.6.1/hardware/jantje/avr_local/variants/standard/pins_arduino.h:28:26: fatal error: avr/pgmspace.h: 그런 파일이나 디렉터리가 없습니다
 #include <avr/pgmspace.h>
                          ^
compilation terminated.
make: **\* [.ino.cpp.o] Error 1

09:57:21 Build Finished (took 913ms)

**Comment by jantje** [comment]
With me it is only a warning.
Please make an empty pgmspace.h file.
Best regards
Jantje

**Comment by kshok** [comment]
Thank your advice.
Step [ make an empty pgmspace.h file ] successfully completed.
also next step [Setting up a debug configuration.] as shown below.
![20150721_debug](https://cloud.githubusercontent.com/assets/13166935/8800996/3a860036-2ff2-11e5-9c65-4c68826cbb95.png)

also below after ctrl+b 
----- below ----
other Building is successfully completed.
.................................................................
Building file: /opt/arduino-1.6.1/hardware/jantje/avr_local/cores/arduino/defines.cpp
Starting C++ compile
"g++" -c -g -O0 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -DF_CPU=16000000L -DARDUINO=10601 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR_LOCAL   -DLOCAL_RUN   -I"/opt/arduino-1.6.1/hardware/jantje/avr_local/cores/arduino" -I"/opt/arduino-1.6.1/hardware/jantje/avr_local/variants/standard" -MMD -MP -MF"arduino/defines.cpp.d" -MT"arduino/defines.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "/opt/arduino-1.6.1/hardware/jantje/avr_local/cores/arduino/defines.cpp"  -o  "arduino/defines.cpp.o"   -Wall
Finished building: /opt/arduino-1.6.1/hardware/jantje/avr_local/cores/arduino/defines.cpp

Starting archiver
"ar" rcs  "/home/ace/workspace/debugDemo/Debug/arduino.ar"    ./arduino/eeprom.cpp.o ./arduino/wdt.cpp.o  ./arduino/Arduino.cpp.o ./arduino/HardwareSerial.cpp.o ./arduino/Print.cpp.o ./arduino/Stream.cpp.o ./arduino/WMath.cpp.o ./arduino/WString.cpp.o ./arduino/defines.cpp.o 
Finished building: arduino.ar

Starting combiner
"g++" -Os  -Wl,--gc-sections -mmcu=atmega328p  -o "/home/ace/workspace/debugDemo/Debug/debugDemo.exe"    ./.ino.cpp.o   arduino.ar   "/home/ace/workspace/debugDemo/Debug/arduino.ar" "-L/home/ace/workspace/debugDemo/Debug" -lm -lpthread
g++: error: unrecognized command line option ‘-mmcu=atmega328p’
make: **\* [debugDemo.elf] 오류 1 (<---error 1)

21:52:37 Build Finished (took 3s.325ms)

Best regards
Mr. Kim

**Comment by jantje** [comment]
so you can debug now?

**Comment by kshok** [comment]
Not yet..
Sorry.

**Comment by jantje** [comment]
:-)
I'll change the title to add pgmspace.h file

**Comment by kshok** [comment]
see make: **\* [debugDemo.elf] 오류 1 (<---error 1)

**Comment by jantje** [comment]
seems your version of gcc has a problem with the -mmcu part of the command while mine has none

> Starting combiner
> "g++" -Os  -Wl,--gc-sections -mmcu=atmega328p  -o "/home/jan/workspaces/arduino/Robot/batterijlader/debug/batterijlader.exe"    ./ChargerBrains.cpp.o ./batterijlader.cpp.o  ./Libraries/gps_Library/gps_Library.cpp.o  ./Libraries/Wire/Wire.cpp.o  ./Libraries/VoltMeter/VoltMeter.cpp.o  ./Libraries/SoftwareSerial/SoftwareSerial.cpp.o  ./Libraries/Servo/Servo.cpp.o  ./Libraries/SerialStringReader/SerialStringReader.cpp.o  ./Libraries/SerialDataInterface/FieldInfo.cpp.o ./Libraries/SerialDataInterface/SerialDataInterface.cpp.o  ./Libraries/SerialCommunicator/SerialCommunicator.cpp.o  ./Libraries/SerialBridgeCommunicator/SerialBridgeCommunicator.cpp.o  ./Libraries/JanServo/JanServo.cpp.o  ./Libraries/I2CLiquidCrystal/I2CLiquidCrystal.cpp.o  ./Libraries/DataTypes/DataTypes.cpp.o  ./Libraries/CurrentSensor/AmpMeter.cpp.o ./Libraries/CurrentSensor/LemCurrentSensor.cpp.o   arduino.ar   "/home/jan/workspaces/arduino/Robot/batterijlader/debug/arduino.ar" "-L/home/jan/workspaces/arduino/Robot/batterijlader/debug" -lm -lpthread
> Finished building: batterijlader.elf

can you mod the platform.txt and change 

## Combine gc-sections, archives, and objects

recipe.c.combine.pattern="{compiler.path}{compiler.c.elf.cmd}" {compiler.c.elf.flags} -mmcu={build.mcu} {compiler.c.elf.extra_flags} -o "{build.path}/{build.project_name}.exe" {object_files} "{build.path}/{archive_file}" "-L{build.path}" -lm -lpthread

to 

## Combine gc-sections, archives, and objects

recipe.c.combine.pattern="{compiler.path}{compiler.c.elf.cmd}" {compiler.c.elf.flags}  {compiler.c.elf.extra_flags} -o "{build.path}/{build.project_name}.exe" {object_files} "{build.path}/{archive_file}" "-L{build.path}" -lm -lpthread

open the project properties and select apply after changing the files to progress the changes to eclipse.

**Comment by kshok** [comment]
Hi

## I had mod successfully the platform.txt 

Building target: debugDemo
Printing size:
ls -lrt "/home/ace/workspace/debugDemo/Debug/debugDemo.exe"
-rwxrwxr-x 1 ace ace 39860  7월 22 10:35 /home/ace/workspace/debugDemo/Debug/debugDemo.exe
Finished building target: debugDemo

## but popup error window .

![20150722_launching](https://cloud.githubusercontent.com/assets/13166935/8816249/42fb299a-305f-11e5-99e6-f247037ed224.png)
how can I?

**Comment by jantje** [comment]
https://cloud.githubusercontent.com/assets/13166935/8800996/3a860036-2ff2-11e5-9c65-4c68826cbb95.png
It looks like the gdb (dsf) process launcher doesn't work on your system.
I refer to the following quote in the blogpost http://blog.baeyens.it/#post23:

> Here you will have to experiment a bit with the settings. On my system I have to use the "legacy create process launcher". I use the settings as shown below.

Try the other debuggers until you find something that works on your system.

Please report what works for you.

**Comment by kshok** [comment]
Wow!!
I did successfully Debugging as below.
change  "legacy create process launcher". 
![20150722_debugging](https://cloud.githubusercontent.com/assets/13166935/8826067/d19a557c-30be-11e5-94a6-88f06ac8e3be.png)

also Debugging 
![20150722_debugging2](https://cloud.githubusercontent.com/assets/13166935/8826093/f01cc6f6-30be-11e5-85cc-9fcabf1698ca.png)

I will try Debugging arduino with EclipseMars for win7 and MinGW.
Thank your information.
Mr.KIm

**Comment by jantje** [comment]
cool :-)

**Comment by jantje** [comment]
Fixed the -mmcu and the missing pgmspace.h file
