### ISSUE TITLE
In MacOS, when compile show error "ld: unknown option: --gc-sections"

### ISSUE THREAD

**Issue by mihayinoviki** [jantje/hardware#7]
in macOS clang compiler not supports --gc-sections options, can instead of -dead_strip options.  My question is how to change makefile, because of generated file, it will refresh back every time. Thanks!

**Comment by jantje** [comment]
modify the platform.txt to make the "recipe" like you want it.
Save the platform.txt
goto you project properties->arduino->apply->close

The new settings should be active
